=== AnaNava1996/EduPlanet/PROYECTO/ProyectoWeb/build/web/data/login.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="class">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="usuario" maxOccurs="unbounded">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="nombre" type="xs:string"/>
                      <xs:element name="tipo" type="xs:string"/>
                      <xs:element name="password">
                          <xs:simpleType>
                              <xs:restriction base="xs:string">
                                  <xs:minLength value="6"/>
                                  <xs:maxLength value="18"/>
                              </xs:restriction>
                          </xs:simpleType>
                      </xs:element>
                  </xs:sequence>
              </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AnaNava1996/EduPlanet/PROYECTO/ProyectoWeb/web/data/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="login.xsd">
    <usuario>
        <nombre>Peredo</nombre>
        <tipo>Profesor</tipo>
        <password>bobesponja</password>
    </usuario>

    <usuario>
        <nombre>Ana</nombre>
        <tipo>Admin</tipo>
        <password>bobesponja</password>
    </usuario>

    <usuario>
        <nombre>Chespirito</nombre>
        <tipo>Alumno</tipo>
        <password>bobesponja</password>
    </usuario>

</class>
